/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import classes.Cliente;
import classes.ETipoPet;
import classes.Pets;
import dados.DadosPets;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vifer
 */
public class FCadastraCliente extends javax.swing.JDialog {
          private Cliente clienteTemp = null;
          private List<Pets> petsTemp = new ArrayList<>();
          private boolean altera = false;
    /**
     * Creates new form FCadastraCliente
     */
    public FCadastraCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.carregaComboTipoPet();
    }
    
    public Cliente execute(){
        this.setVisible(true);
        return this.clienteTemp;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaNome = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        etiquetaTipoPet = new javax.swing.JLabel();
        ComboTipoPet = new javax.swing.JComboBox<>();
        etiquetaPetNome = new javax.swing.JLabel();
        CampoPetNome = new javax.swing.JTextField();
        etiquetaPetIdade = new javax.swing.JLabel();
        campoPetIdade = new javax.swing.JTextField();
        radioCastradoSim = new javax.swing.JRadioButton();
        radioCastradoNao = new javax.swing.JRadioButton();
        etiquetaCastrado = new javax.swing.JLabel();
        etiquetaTelefone = new javax.swing.JLabel();
        campoFormatTelefone = new javax.swing.JFormattedTextField();
        botaoAddPet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPets = new javax.swing.JTable();
        botaoCadastraCliente = new javax.swing.JButton();
        botaoCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        etiquetaNome.setText("Nome");

        etiquetaTipoPet.setText("Pet (Tipo)");

        etiquetaPetNome.setText("Pet (Nome)");

        etiquetaPetIdade.setText("Pet (Idade)");

        buttonGroup1.add(radioCastradoSim);
        radioCastradoSim.setSelected(true);
        radioCastradoSim.setText("Sim");

        buttonGroup1.add(radioCastradoNao);
        radioCastradoNao.setText("Não");

        etiquetaCastrado.setText("Castrado?");

        etiquetaTelefone.setText("Telefone");

        try {
            campoFormatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoAddPet.setText("Adicionar");
        botaoAddPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddPetActionPerformed(evt);
            }
        });

        tabelaPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Pet", "Tipo do Pet", "Idade", "Castrado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPets);
        if (tabelaPets.getColumnModel().getColumnCount() > 0) {
            tabelaPets.getColumnModel().getColumn(0).setResizable(false);
            tabelaPets.getColumnModel().getColumn(1).setResizable(false);
            tabelaPets.getColumnModel().getColumn(2).setResizable(false);
            tabelaPets.getColumnModel().getColumn(3).setResizable(false);
        }

        botaoCadastraCliente.setText("Cadastra Cliente");
        botaoCadastraCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastraClienteActionPerformed(evt);
            }
        });

        botaoCancela.setText("Cancela");
        botaoCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(etiquetaNome))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFormatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaPetNome)
                                .addGap(93, 93, 93)
                                .addComponent(etiquetaTipoPet))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CampoPetNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(ComboTipoPet, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPetIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPetIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioCastradoSim)
                            .addComponent(etiquetaCastrado)
                            .addComponent(radioCastradoNao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(botaoAddPet)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoCancela)
                .addGap(51, 51, 51)
                .addComponent(botaoCadastraCliente)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNome)
                    .addComponent(etiquetaTelefone))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFormatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPetNome)
                    .addComponent(etiquetaTipoPet)
                    .addComponent(etiquetaPetIdade)
                    .addComponent(etiquetaCastrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPetNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboTipoPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPetIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCastradoSim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioCastradoNao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAddPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastraCliente)
                    .addComponent(botaoCancela))
                .addGap(54, 54, 54))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelaActionPerformed
        this.clienteTemp = null;
        this.setVisible(false);
    }//GEN-LAST:event_botaoCancelaActionPerformed

    private void botaoAddPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddPetActionPerformed
         Pets pet = new Pets();
         pet.setNomePet(CampoPetNome.getText());
         if(ComboTipoPet.getSelectedIndex()>-1){
             pet.setTipoPet(DadosPets.obterTipo(ComboTipoPet.getSelectedItem().toString()));
         }
         pet.setIdadePet(Integer.parseInt(campoPetIdade.getText()));
            if(radioCastradoSim.isSelected()){
                pet.setCastrado(true);
            }
            else{
                pet.setCastrado(false);
            }
            petsTemp.add(pet);
            this.carregaTabelaPets(petsTemp);
            CampoPetNome.setText("");
            campoPetIdade.setText("");
    }//GEN-LAST:event_botaoAddPetActionPerformed

    private void botaoCadastraClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastraClienteActionPerformed
       Cliente cliente = new Cliente();
       cliente.setNome(nomeCliente.getText());
       cliente.setTelefone(campoFormatTelefone.getText());
       cliente.setPet(petsTemp);
       cliente = this.clienteTemp;
       JOptionPane.showMessageDialog(this, "Cliente Cadastrado!");
       this.setVisible(false);
    }//GEN-LAST:event_botaoCadastraClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregaTabelaPets(List<Pets> listaPets){
       DefaultTableModel modelo = (DefaultTableModel)tabelaPets.getModel();
            modelo.getDataVector().removeAllElements();
                for (Pets pet : listaPets){
                    Vector vt = new Vector();
                    vt.add(pet.getNomePet());
                    vt.add(pet.getTipoPet().getText());
                    vt.add(pet.getIdadePet().toString());
                     if(pet.getCastrado()){
                         vt.add("Sim");
                     }
                     else{
                         vt.add("Não");
                     }
                    modelo.addRow(vt);
                } 
                
            tabelaPets.repaint();
    }
    
    private void carregaComboTipoPet(){
        ComboTipoPet.removeAllItems();
        for (ETipoPet tipoPet: ETipoPet.values()){
            ComboTipoPet.addItem(tipoPet.getText());
        }
        ComboTipoPet.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadastraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadastraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadastraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadastraCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FCadastraCliente dialog = new FCadastraCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoPetNome;
    private javax.swing.JComboBox<String> ComboTipoPet;
    private javax.swing.JButton botaoAddPet;
    private javax.swing.JButton botaoCadastraCliente;
    private javax.swing.JButton botaoCancela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField campoFormatTelefone;
    private javax.swing.JTextField campoPetIdade;
    private javax.swing.JLabel etiquetaCastrado;
    private javax.swing.JLabel etiquetaNome;
    private javax.swing.JLabel etiquetaPetIdade;
    private javax.swing.JLabel etiquetaPetNome;
    private javax.swing.JLabel etiquetaTelefone;
    private javax.swing.JLabel etiquetaTipoPet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JRadioButton radioCastradoNao;
    private javax.swing.JRadioButton radioCastradoSim;
    private javax.swing.JTable tabelaPets;
    // End of variables declaration//GEN-END:variables
}
